databases:
  - name: e-commerce
    databaseName:  PostgreSQL
    user: fayth

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name:  PostgreSQL 
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  # - type: redis
  #   name: redis
  #   ipAllowList: []
  #   plan: free
  #   maxmemoryPolicy: noenviction
